### ISSUE TITLE
Urban 100 dataset can not download

### ISSUE THREAD

**Issue by gdyshi** [YeongHyeon/Super-Resolution_CNN#2]
The Urban 100 data set in the reference is not available.
Can you give me a new link for Urban 100 dataset? 
Thanks
![image](https://user-images.githubusercontent.com/6500274/92450242-c1409600-f1ed-11ea-9ee9-cb43e3154cf3.png)

**Comment by weizhiliang0520** [comment]
> The Urban 100 data set in the reference is not available.
> Can you give me a new link for Urban 100 dataset?
> Thanks
> ![image](https://user-images.githubusercontent.com/6500274/92450242-c1409600-f1ed-11ea-9ee9-cb43e3154cf3.png)

could  you please tell me how to change the png(or jpg)img to img.npy?thank you!

**Comment by YeongHyeon** [comment]
Sorry for the late response.

You may access the other URL as follows.

https://huggingface.co/datasets/eugenesiow/Urban100
https://www.kaggle.com/datasets/harshraone/urban100

Also, you can find the above links on Google.
Thank you for your interest.
